<?php

namespace Blogger\BlogBundle\Entity\Repository;

use Blogger\BlogBundle\Entity\Comment;
use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    /**
     * @param int $postId
     * @param bool $approved
     * @return Comment[]
     */
    public function getCommentsForPost($postId, $approved = true)
    {
        $qb = $this->createQueryBuilder('c')
            ->select('c')
            ->where('c.post = :post_id')
            ->addOrderBy('c.created')
            ->setParameter('post_id', $postId);

        if (false === is_null($approved)) {
            $qb->andWhere('c.approved = :approved')->setParameter('approved', $approved);
        }

        return $qb->getQuery()->getResult();
    }
}
